version: '3'

services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  gallery_backend:
    container_name: gallery_backend
    image: node:alpine3.16
    working_dir: /gallery/backend
    restart: always
    command: sh -c "yarn --check-files && yarn dev"
    ports:
      - 3200:3200
    volumes:
      - .:/gallery/backend
    links:
      - mongo
volumes:
  mongodb_data:
    driver: local
